### ISSUE TITLE
Read more link

### ISSUE THREAD

**Issue by adekoyejoakinhanmi** [micjamking/succinct#10]
I really like the plugin as a matter of fact I will be using for my next project. I realized that succinct only truncates the desired text it doesn't a read more link that can allow readers finish reading the article. I do like to mention that I av not fully checked it out so if the read more function is already there please ignore else please update. Thanks.

**Comment by sfowles** [comment]
Do you still have that version you modified, brzrkr? The link to your Gist seems to have died.

**Comment by brzrkr** [comment]
Sure thing, I believe it's because I changed my username. Should be visible here: https://gist.github.com/brzrkr/9415a1de25324509b413

**Comment by JordanSayner** [comment]
Im liking your modification @brzrkr . How easy would it be to make it so I can truncate text if the window size is lower than 768px? while using the resize function.

I have added and if state around around the function that fires succinct but that does untruncate once it has truncated the text.

Any help would be appreciated

**Comment by adrianratajczak** [comment]
@JordanSayner hi, u can use hack like this:
```
function succinct_add() {
            $(function(){
                if ($(window).width() <768) {
                    $('.name_ellipsis').succinct({
                        size: 38
                    });
                }
                else {
                    $('.name_ellipsis').succinct({
                        size: 50
                    });
                }
            });
        .
    succinct_add();
    $(window).resize(function(){
        succinct_add();
    })
```

in else type ultra big number, that will simulate untruncate;
